import '../styles/globals.sass'
import '../code-examples/nexus-tbc-builds/app/ClassicBuilds.sass'

import type { AppProps } from 'next/app'
import Head from 'next/head'

import ThemeProvider from '../contexts/theme'
import AppContainer from '../layout/AppContainer'

function App({ Component, pageProps }: AppProps) {

  return (
    <>
      <Head>
        <meta charSet="utf-8" />
        <title>Zac Miller</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta key="robots" name="robots" content="nofollow, noindex" />
        <meta key="viewport" name="viewport" content="width=device-width, maximum-scale=1.0, user-scalable=0, initial-scale=1" />
      </Head>
      <ThemeProvider>
        <AppContainer>
          <Component {...pageProps} />
        </AppContainer>
      </ThemeProvider>
    </>
  )
}

export default App
